<a href="https://colab.research.google.com/github/BrainConnection/Schroedinger-Practice/blob/main/Slinky%20Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Environment Setting

In [1]:
!pip install numpy

In [2]:
import numpy as np

# 1. Point Mass Modeling

In [13]:
# Constant Initialization

N = 3                     # # of point mass
omega = 2 * np.pi * 10      # w**2 := k/m, Hz
g = 9.8                     # m/s**2

In [ ]:
# Position initialization

y_0 = []

In [14]:
# Matrix A Construction & Diagonalization

lst = []

for i in range(N+1):

  if i==0:
    sub_lst = []
    for j in range(N+1):

      if j==0:
        sub_lst.append(-1)

      elif j==1:
        sub_lst.append(+1)

      else:
        sub_lst.append(0)

  elif i==N:
    sub_lst = []
    for j in range(N+1):

      if j==N-1:
        sub_lst.append(+1)

      elif j==N:
        sub_lst.append(-1)

      else:
        sub_lst.append(0)

  else:
    sub_lst = []
    for j in range(N+1):

      if j==i-1:
        sub_lst.append(+1)

      elif j==i:
        sub_lst.append(-2)

      elif j==i+1:
        sub_lst.append(+1)

      else:
        sub_lst.append(0)

  lst.append(sub_lst)

A = np.array(lst)

In [15]:
A

array([[-1,  1,  0,  0],
       [ 1, -2,  1,  0],
       [ 0,  1, -2,  1],
       [ 0,  0,  1, -1]])

In [21]:
D, P = np.linalg.eig(A)
P_dag = np.linalg.inv(P)

In [22]:
D

array([-3.41421356e+00, -2.00000000e+00, -9.23055176e-17, -5.85786438e-01])

In [23]:
P

array([[-0.27059805, -0.5       , -0.5       , -0.65328148],
       [ 0.65328148,  0.5       , -0.5       , -0.27059805],
       [-0.65328148,  0.5       , -0.5       ,  0.27059805],
       [ 0.27059805, -0.5       , -0.5       ,  0.65328148]])

In [24]:
P_dag

array([[-0.27059805,  0.65328148, -0.65328148,  0.27059805],
       [-0.5       ,  0.5       ,  0.5       , -0.5       ],
       [-0.5       , -0.5       , -0.5       , -0.5       ],
       [-0.65328148, -0.27059805,  0.27059805,  0.65328148]])